name: pinns_tf_2_4
channels:
  - defaults
dependencies:
  - joblib=1.0.1
  - pandas=1.2.4
  - pip=21.1.1
  - python=3.7.10
  - python-dateutil=2.8.1
  - pytz=2021.1
  - scipy=1.6.2
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.12.0
    - astunparse==1.6.3
    - cachetools==4.2.2
    - chardet==4.0.0
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.30.1
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==2.10
    - importlib-metadata==4.5.0
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - protobuf==3.17.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.0
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.5
    - werkzeug==2.0.1
    - wrapt==1.12.1
    - zipp==3.4.1
